### ISSUE TITLE
Brawl Stars v49.175

### ISSUE THREAD

**Issue by Manan2004** [risporce/Supercell-jailbreak#1]
Brawl Stars v49.175 ipa without jailbreak detection please?

**Comment by risporce** [comment]
hi, supercell started shipping their new updates with a new protector called promon, the jailbreak detection of promon cannot be bypassed by simple techniques like i was doing before.
I am currently looking at it the little time i have to see if i can do something about it.
hopefully yes because how promon work is that once you have jailbroke your device, even if you reboot or remove the jb, it will still detect some files has been modified it which is very annoying.

**Comment by risporce** [comment]
> Brawl Stars v49.175 ipa without jailbreak detection please?

now added ;)
