### ISSUE TITLE
Any reports of possible bans?

### ISSUE THREAD

**Issue by GrantsUsername** [risporce/Supercell-jailbreak#13]
First off, thank you very much for the mod and contribution.

You mention that you haven’t been banned from using modded ipa’s for the past two years, but I was just wondering if there have been any recent reports of any bans from using any of these ipa’s? Not sure how they’d even be able to detect the modded ipa on their end.

Then again, bottom line just use at your own risk like you mentioned I suppose - just thought I’d ask around.

**Comment by risporce** [comment]
> First off, thank you very much for the mod and contribution.
> 
> You mention that you haven’t been banned from using modded ipa’s for the past two years, but I was just wondering if there have been any recent reports of any bans from using any of these ipa’s? Not sure how they’d even be able to detect the modded ipa on their end.
> 
> Then again, bottom line just use at your own risk like you mentioned I suppose - just thought I’d ask around.

Hi, as of right now, i still haven't get any case of player banned from using the ipas, but it doesn't mean it won't happen, Supercell doesn't know the existence of this repo probably yet and when they will they will strike the repo. That's why i'm actively trying to make is a static bypass in a deb tweak this way the chance of it being detected will be significantly reduced and also supercell couldn't strike this repo.
