### ISSUE TITLE
Clash Royale on IOS 12

### ISSUE THREAD

**Issue by lebakasable** [risporce/Supercell-jailbreak#30]
Why the given IPA file requires IOS 13 but the official app on Apple Store requires only IOS 11 ?

**Comment by risporce** [comment]
looks like i forgot to change it back to iOS 11+ to for clash royale. It will be fixed in the next clash royale update that is actually coming soon

In the meantime, if you encounter the same issue. simply extract the ipa, open info.plist and change `MinimumOSVersion` to `11.0` instead of the current `13.0` . then compile back "Payload" folder to zip and rename to .ipa, then install, your ipa will now support ios 11 and 12 if you have a device in this range of ios versions
