### ISSUE TITLE
Squad busters save resets

### ISSUE THREAD

**Issue by TV46** [risporce/Supercell-jailbreak#42]
Whenever you close and reopen the squad busters app your save resets back to the start of the tutorial

**Comment by risporce** [comment]
Hi, note that this is completely out of my control normally you should ask supercell support for that kind of problem, but you’re lucky because I got that problem and I can tell you a way to fix it .

first, use something like Apps Manager and clear squad busters app data 
Second, reopen it, but DONT connect to supercell id before finishing the Third game you’ve played, this way you should be able to permanently save your account in supercell id

**Comment by TV46** [comment]
Thank you
