### ISSUE TITLE
Apk support?

### ISSUE THREAD

**Issue by dtingley11** [risporce/Supercell-jailbreak#48]
Hello, I've been using all of your apks for clash of clans and they work great! Thank you for all of your work 🙏 we appreciate it! 

Seems like with this latest update they implemented a new root checking method for Android. Do you know if there is a bypass or is this something you won't work on at all. I'm just wondering if you know anything about it! 

Thanks again!

**Comment by risporce** [comment]
I completely stopped working since more than a year on the protection in supercell games, on iOS moreover, i don't even have an android device, emulators don't work the same as physical device so it wouldn't work testing on them anyway

From what I heard, people can play fine Supercell games with magisk root hide, have you tried that? (i don't know about other root, that's what i remember from other people's experience)

So no, here there will never be Supercell apks with root bypass, sorry.

**Comment by dtingley11** [comment]
Ah, silly me. I forgot to install shamiko. Clash of clans works once again!

Makes sense, thank you!
