### ISSUE TITLE
Hay Day 1.63.204

### ISSUE THREAD

**Issue by Anatharias** [risporce/Supercell-jailbreak#65]
Hello,
Thanks for your work onto making it possible to play SuperCell games on Jailbroken devices.

However, since this update, as soon as you exit the game (Hay Day 1.63.204), it logs you out entirely.
It does not retrieve the save state from the Game Center

when I say "exit the app" it could also be turning off the ipad for 5 minutes and opening it again ..

Thanks for looking onto this

**Comment by risporce** [comment]
Hi, you should register your account to Supercell Id, this way your progress will never be lost and it will always load your account correctly every time you open the game.

**Comment by Anatharias** [comment]
Hey, thanks for replying.
I definitely have a Supercell account, to which my progress is saved. 

However, whenever I launch the game after an idle time, I must re-login.
So, the initial video, followed by a short tutorial on how to use the game, followed by a message to restore the progress.
Followed by entering your email address, getting a one time code and then finally get to your game.

Definitely not ideal. Maybe one of the files you modified is in read-only, preventing the game from properly saving its login information, idk, just a though

**Comment by risporce** [comment]
Hey, sorry for long reply, can you try what i just added in Faq section?:
https://github.com/risporce/Supercell-jailbreak?tab=readme-ov-file#the-game-reset-its-progress-every-time-i-open-it-why-how-to-fix-it

This is a bug that even me get occasionally i'm not sure why but this fixes the issue when i get this, you should give it a try !

**Comment by Anatharias** [comment]
Hello, I've proceeded with this cleaning, however, this has not changed the app login issue that keeps on popping up every time I launch the game :-(
Any other idea ?
Thanks

**Comment by risporce** [comment]
I'm still pretty sure it's just some file corruptions with your device filesystem, but it's odd that the cleaning didn't help because usually when i get into that situation, this fix the problem.

I don't modify anything in Hay Day or other supercell games other than the main executable only and it's only to patch what the protector is re-building in runtime. In other words, i'm certain that this is not cause by the patch.

I don't really have any other idea, but you could still try something tho which will help clear all the cache on your device.

Do the same procedure as i said before with Apps Manager, so wipe data and delete **ALL** Hay Day apps you have.
Now reboot your device, not a soft reboot, a normal reboot which will get you back in jailed mode.
You may as well now either jailbreak back right away or install Hay Day again and test it. By rebooting, this should really fix all filesystem and refresh all cache which doesn't happen when in jailbroken mode, Hopefully this fixes the issue.
