### ISSUE TITLE
Not install

### ISSUE THREAD

**Issue by Hit1ove** [risporce/Supercell-jailbreak#69]
I did everything, but when installing via sideloadly, it gives an error, also not installing on a device with Jailbreal.
Error in Sideloadly:

Checking private key
Looking up app ID
Using app ID "Brawl Stars" with id U86Q9F4J98
Provisioning profile TTL: 7 days, local: True
Signing...
ERROR: Guru Meditation 7c026a@447:14dd8f ('expected 97, found 17', FieldError(FieldError('expected 4, found 0')))
Install failed: Guru Meditation 7c026a@447:14dd8f ('expected 97, found 17', FieldError(FieldError('expected 4, found 0')))

**Comment by risporce** [comment]
Hi, this is due to running the script multiples time in a row, this is fixed in the new version so it won't break load commands anymore.
So get a clean IPA of your application and try again to execute the script but make sure to only execute it once as the script doesn't create a backup of the executable.
