### ISSUE TITLE
Help Pls

### ISSUE THREAD

**Issue by shadow-mafi** [risporce/Supercell-jailbreak#75]
**i executed the command and succeed i think** 

```
C:\Users\shado\Downloads\Supercell-jailbreak-main\Supercell-jailbreak-main>python sc_protector_file_parser.py --game "Hay Day"
[INFO] Found LC_DYLD_INFO_ONLY at offset at : 0x1218
[INFO] Found string table fixing address at: 0x2461fe8
[INFO] Found symbol table start address at: 0x2662290
[INFO] Found protector loader at: 0x1348
[INFO] setup done, don't exit, the computer can take up to a minute to exit frida session
[INFO] removed protector loader
[INFO] fixed export functions data and size
[SUCCESS] finished fixing binary file, you may now exit pressing CTRL+C
[DEBUG] Duration: 0:00:01.943100
```

then i replaced the executable file with the orijinal file in the folder and after that i compressed the payload folder into zip and renamed it into ipa format after that i uninstalled the orijinal game on my phone and installed the ipa with trollstore lite but i had no chance the game crashed on the black screen again.

**Comment by risporce** [comment]
You said "replaced the executable file with the orijinal file". If that’s really what you did, well you need to use the new patched executable in the app and replace the existing binary file by the new one, but I assume that’s what you meant but just didn’t write it correctly 

So another reason could be that I saw the trouble you had earlier with the usb cable, if the script didn’t managed to get all the necessary data, then it’s possible that it still crash, try again on a fresh new binary file, I just re-tested the current version of the script with Hay Day and it works fine for me. I believe there was some issues with the data and it caused it to not patch all the binary correctly 

Finally, the current version of the script have a bug where running the script multiples times on the same binary will break the executable binary, so always get a fresh new binary executable to run the script on. This will be fixed in the next update where I add many safety checks that are necessary for people to understand better what is happening and making sure this situation doesn’t reproduce
