### ISSUE TITLE
Step by step guide with pictures?

### ISSUE THREAD

**Issue by hasan-elhuseyin** [risporce/Supercell-jailbreak#81]
It would be amazing if we can have a step by step guide for these steps, I have everything done but yet I'm not successful in making this work (with brawl starts). I feel like I'm really close, yet not sure what I'm missing.
A step by step guide would be highly appreciated.

**Comment by risporce** [comment]
Hello, 
Tell me which steps would you like to see more information and or maybe an image and also what would you like me describe more? Tell me which steps you didn't understand and how could i improve the current step-by-step guide.

Right now, i have planned to add a troubleshoot section since many people seems to have issues with Frida, i'll put reference to some fix for their issues.

Also, where are you currently stuck at? can you show me a screenshot of the current terminal output for the script (if you're tried running it) or what do you not understand and what have you tried.

If you prefer to talk to me on Discord or Telegram, you can find me with the username risporce

**Comment by VuHoangLong2k1** [comment]
If anyone has done it, please share the ipa with me 🙇🏻🙇🏻

**Comment by rclean** [comment]
[https://github.com/rclean/Supercell-jailbreak-Clash-of-Clans](https://github.com/rclean/Supercell-jailbreak-Clash-of-Clans)   here can download new version support TH17. thanks rispoce uploading ipa for more than 1 years

**Comment by hasan-elhuseyin** [comment]
@risporce yes of course, here's a step by step of everything I tried:

1. First I started by downloading the ipa of Brawl Stars from the internet.

2. Then I installed all required packages both on my iPad and MacBook, I confirmed that everything is ok by running 'frida-ps -U' and checking the pid list.

![Screenshot 2024-11-28 at 12 19 21](https://github.com/user-attachments/assets/e6bbcd82-a9af-4297-ae59-56aefe84f89f)

3. The steps says to extract the ipa file which I was a little bit confused about, I was not sure how to extract it so I changed the extension of the file from .ipa to .zip and extracted it like that.

![Screenshot 2024-11-28 at 12 34 30](https://github.com/user-attachments/assets/1e0a1b43-788d-4efd-9ae6-032afa082fe8)

4. Since I was able to see the 'Payload' folder I assumed that everything is going well.
Inside 'Payload' I can see 'laser.app' which I also assumed is not the executable file that I'm looking for, so I went inside of that and found an executable called 'laser'.
At this point I wasn't sure If I had to move this executable file out and work with it, or just to bring the script in, I chose to bring the script and paste it inside laser.app

![Screenshot 2024-11-28 at 12 38 34](https://github.com/user-attachments/assets/cc4ed6cd-8866-4932-ab4c-d9237e626c79)

5. I executed ``` python3 sc_protector_file_parser.py --game "laser" ``` but got an error and here's where I'm currently blocked.

![Screenshot 2024-11-28 at 12 26 42](https://github.com/user-attachments/assets/4a2081b3-8a96-41ce-a86c-859f1fd069ae)

**Comment by hasan-elhuseyin** [comment]
.

**Comment by hasan-elhuseyin** [comment]
Update:

- Just for good measures, I put my MacBook in recovery mode and went to disable SIP completely.
But I still get the same error as before.

![Screenshot 2024-11-28 at 13 29 24](https://github.com/user-attachments/assets/1b660f26-c895-483a-b280-c675e50de47c)

![Screenshot 2024-11-28 at 13 33 01](https://github.com/user-attachments/assets/2af97361-12dc-4d35-a3e6-c380719611ea)

**Comment by rldv1** [comment]
error related to function which tries to check boot-args (to try use your  macbook instead of an iphone for the patch) apparently there are some problems with this, if you have a jailbroken iphone - try to remove bootargs check (replace it to return False)

**Comment by risporce** [comment]
Hey, First of, you don't necessarily need a Mac, the script just has an option to use your Mac with M series chip to do the patching, but any computer can do the job.

It is normal that when executing the script, you see the game open and close pretty fast, this is expected behavior has the script don't allow to load and play the game while jailbroken, it's only to gather necessary information from the protector needed to make the patching in the executable file of the ipa you got on your computer.

So you can use the script on any computer you have, try it and if you're stuck somewhere tell me where and what have you tried so i can guide you in the right direction

> Did they make it? Can I fix it? I got to the part that I synchronize with my iPhone since I have no Mac but asks me to open the app on it and this is closed instantly so it is impossible for me, I know what is the executable If I could you can. Share the ipa of Squad buster? And if I can't help you

**Comment by Puchet0** [comment]
Thanks, I had already given up because after re-creating the ipa the app would not start.
I tried again but this time removing the executable and it worked.

**Comment by Alzentane** [comment]
Here 

https://www.mediafire.com/file/zptku3dnnk3cewk/Brawl_Stars_NJ.ipa/file
